---
name: Clippy

# Trigger the workflow on push or pull request
"on":
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: clippy,rustfmt
      - name: "Run clippy"
        run: cargo clippy --all-targets
      - name: Run fmt
        run: cargo fmt --check
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
