---
name: Rust Testing
"on":
  push:
    branches:
      - main
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - uses: cargo-bins/cargo-binstall@e00d2c94cc0067b77737821097a62d91c0301baa # v1.21.1
      - name: Install cargo-tarpaulin
        run: cargo binstall cargo-tarpaulin --no-confirm

      - name: "Run cargo test with coverage"
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --workspace --all-features --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: github.actor != 'dependabot[bot]'
      - name: "Run cargo test without coverage"
        run: |
          cargo test --workspace --all-features
        if: github.actor != 'dependabot[bot]'
      - name: "Build the workspace (release)"
        run: cargo build --workspace --release
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
